In [8]:
import numpy as np
import pandas as pd
data = pd.DataFrame(np.random.randn(1000, 4)*4)
print(data)
data.describe()

            0          1         2          3
0    5.905771  -8.415463 -7.176111  -4.481787
1   -2.587777   1.407457 -3.233366   2.074764
2   -1.455838  -2.530399  3.786781   4.530536
3   -0.173371  -1.051906  0.961270  -4.179853
4   -6.260758   0.124404 -4.296542  -4.583118
5    6.825281   2.493297 -2.587827  -3.507666
6    2.182936  -3.968735 -6.506197   0.315675
7   -2.241710  -2.081669 -6.675034   2.483937
8   -1.208871  -0.107938 -0.598703  -4.942290
9    1.685643   8.408288  0.832720   2.627328
10  -0.172961   4.082889 -2.443453   1.460125
11   4.206539   4.870974 -1.648655   0.089811
12   5.094541   0.033893  2.403870   0.141339
13  -3.754042   1.959546  0.845129   3.669839
14   5.818603  10.125855  0.214327  -1.666184
15   4.520781  -0.856647  5.829441   0.405231
16   0.084754   8.552905 -0.250849  -9.520371
17   0.570418  -8.475946  4.245641   3.031449
18  -2.330094  -7.878641  1.321786  -3.280195
19  -2.882693   3.063777 -3.321728  -1.883948
20  -1.222876  -0.554166  3.273958  -7.452545
21  -1.828125   7.102746 -0.516741  -3.997871
22   9.209871  -2.622266 -2.948599   2.346407
23  -5.268162  -3.167566 -6.167315   3.577700
24   0.517344  -1.617795  9.723675   1.150533
25  -2.442758   2.481111 -4.850840   2.816266
26   9.925875   3.309526 -1.680072   0.278903
27   3.151408   0.169032  0.905199   0.978858
28   3.585360  -3.080942  2.483043   2.475613
29   7.874233  -2.998974 -0.928555   0.246110
..        ...        ...       ...        ...
970 -2.330559   2.459860 -4.462273  -8.140424
971  1.867922  -1.161246  3.310409   1.657112
972 -5.013924   6.503939  6.410899  -1.823906
973  4.232546   9.571923  6.693685   0.103034
974 -2.829838   1.055137 -1.944812   5.128493
975  1.774997  -2.204958 -1.691871   1.168624
976 -2.484189  -4.163532 -0.440456   0.345072
977  0.065272  -2.669306 -1.400573  -2.244069
978  0.961512   6.618251 -8.604010   3.766782
979  6.450283  -6.968558 -0.446350 -10.761981
980  0.307257  -2.256021  5.787687   2.151629
981  5.867664   6.476644 -4.480702  -3.634790
982  3.373054   3.760324 -4.787072  -0.140680
983 -2.717794   2.584219 -2.073807  -9.947960
984 -0.209749  -0.988538  2.622132   0.307968
985 -1.502332   6.878127  3.837322  -0.671552
986  2.564620  11.349297 -3.237875   8.878686
987 -2.877121   1.022580  3.488385   3.865095
988  3.032334  -1.120698 -1.799012  -0.874585
989  1.939545  -1.388685  0.760593   3.130760
990 -5.021510  -9.691051  1.088058  -3.060264
991 -0.041333  -1.951296  4.850831   2.567996
992  0.739713  -1.427057 -3.065336   6.389519
993 -2.874976   4.417780  4.169037  -0.321310
994 -0.558358  -3.992054 -3.225505   0.534330
995  3.055077  -1.369863  2.901832  -1.624325
996 -5.794644   3.284308  8.419364  -1.183531
997 -0.896029   0.597319  1.711432  -0.917793
998  6.367809  -4.459744  2.040686  -2.324522
999  0.665194   0.690930  5.377604   8.618687

[1000 rows x 4 columns]

                 0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.123415     0.206483     0.178117    -0.113737
std       3.975383     4.036844     4.112980     4.076469
min     -10.625168   -11.609530   -15.356471   -15.228986
25%      -2.792034    -2.569587    -2.425086    -2.669382
50%      -0.173397     0.236340     0.254438    -0.171871
75%       2.550620     3.058304     2.960219     2.570833
max      13.188562    11.739906    13.969092    13.163078

In [10]:
col = data[2]
col

0     -7.176111
1     -3.233366
2      3.786781
3      0.961270
4     -4.296542
5     -2.587827
6     -6.506197
7     -6.675034
8     -0.598703
9      0.832720
10    -2.443453
11    -1.648655
12     2.403870
13     0.845129
14     0.214327
15     5.829441
16    -0.250849
17     4.245641
18     1.321786
19    -3.321728
20     3.273958
21    -0.516741
22    -2.948599
23    -6.167315
24     9.723675
25    -4.850840
26    -1.680072
27     0.905199
28     2.483043
29    -0.928555
         ...
970   -4.462273
971    3.310409
972    6.410899
973    6.693685
974   -1.944812
975   -1.691871
976   -0.440456
977   -1.400573
978   -8.604010
979   -0.446350
980    5.787687
981   -4.480702
982   -4.787072
983   -2.073807
984    2.622132
985    3.837322
986   -3.237875
987    3.488385
988   -1.799012
989    0.760593
990    1.088058
991    4.850831
992   -3.065336
993    4.169037
994   -3.225505
995    2.901832
996    8.419364
997    1.711432
998    2.040686
999    5.377604
Name: 2, Length: 1000, dtype: float64

In [19]:
col[np.abs(col) > 8]

24      9.723675
74      9.585756
93     -9.363438
100   -10.360151
143    -9.248552
166   -15.356471
167     9.078037
168     8.913622
178   -11.379627
194    12.120326
250     8.388327
298   -11.191812
306    11.046400
309    -9.228928
311    -9.754308
324    10.723763
364    -8.245962
373    -8.622637
377     9.338152
411    10.428129
433    -8.591833
439    -8.971495
443    12.822822
522    -8.252888
562    -8.720797
579   -10.085893
587     9.031305
589    -9.812886
611    -8.152803
613    10.139312
638   -14.563030
683    13.588886
686    -8.665990
691    -9.265127
724    -8.037920
744    13.969092
772     8.912590
773    -9.824576
794     8.447495
804    -8.468747
850     9.716063
862    10.022499
901    10.996172
922    -8.688868
930     8.309991
960    10.198746
978    -8.604010
996     8.419364
Name: 2, dtype: float64

In [20]:
data[(np.abs(data) > 3).any(1)]

            0          1         2          3
0    5.905771  -8.415463 -7.176111  -4.481787
1   -2.587777   1.407457 -3.233366   2.074764
2   -1.455838  -2.530399  3.786781   4.530536
3   -0.173371  -1.051906  0.961270  -4.179853
4   -6.260758   0.124404 -4.296542  -4.583118
5    6.825281   2.493297 -2.587827  -3.507666
6    2.182936  -3.968735 -6.506197   0.315675
7   -2.241710  -2.081669 -6.675034   2.483937
8   -1.208871  -0.107938 -0.598703  -4.942290
9    1.685643   8.408288  0.832720   2.627328
10  -0.172961   4.082889 -2.443453   1.460125
11   4.206539   4.870974 -1.648655   0.089811
12   5.094541   0.033893  2.403870   0.141339
13  -3.754042   1.959546  0.845129   3.669839
14   5.818603  10.125855  0.214327  -1.666184
15   4.520781  -0.856647  5.829441   0.405231
16   0.084754   8.552905 -0.250849  -9.520371
17   0.570418  -8.475946  4.245641   3.031449
18  -2.330094  -7.878641  1.321786  -3.280195
19  -2.882693   3.063777 -3.321728  -1.883948
20  -1.222876  -0.554166  3.273958  -7.452545
21  -1.828125   7.102746 -0.516741  -3.997871
22   9.209871  -2.622266 -2.948599   2.346407
23  -5.268162  -3.167566 -6.167315   3.577700
24   0.517344  -1.617795  9.723675   1.150533
25  -2.442758   2.481111 -4.850840   2.816266
26   9.925875   3.309526 -1.680072   0.278903
27   3.151408   0.169032  0.905199   0.978858
28   3.585360  -3.080942  2.483043   2.475613
29   7.874233  -2.998974 -0.928555   0.246110
..        ...        ...       ...        ...
965  5.610202  -8.164948 -1.049547  -2.914672
967  3.584370  -8.547376  1.100019   6.742570
968  7.207547   6.583031 -1.603197  -2.809777
969 -4.878383  -4.387047  4.596089   0.931476
970 -2.330559   2.459860 -4.462273  -8.140424
971  1.867922  -1.161246  3.310409   1.657112
972 -5.013924   6.503939  6.410899  -1.823906
973  4.232546   9.571923  6.693685   0.103034
974 -2.829838   1.055137 -1.944812   5.128493
976 -2.484189  -4.163532 -0.440456   0.345072
978  0.961512   6.618251 -8.604010   3.766782
979  6.450283  -6.968558 -0.446350 -10.761981
980  0.307257  -2.256021  5.787687   2.151629
981  5.867664   6.476644 -4.480702  -3.634790
982  3.373054   3.760324 -4.787072  -0.140680
983 -2.717794   2.584219 -2.073807  -9.947960
985 -1.502332   6.878127  3.837322  -0.671552
986  2.564620  11.349297 -3.237875   8.878686
987 -2.877121   1.022580  3.488385   3.865095
988  3.032334  -1.120698 -1.799012  -0.874585
989  1.939545  -1.388685  0.760593   3.130760
990 -5.021510  -9.691051  1.088058  -3.060264
991 -0.041333  -1.951296  4.850831   2.567996
992  0.739713  -1.427057 -3.065336   6.389519
993 -2.874976   4.417780  4.169037  -0.321310
994 -0.558358  -3.992054 -3.225505   0.534330
995  3.055077  -1.369863  2.901832  -1.624325
996 -5.794644   3.284308  8.419364  -1.183531
998  6.367809  -4.459744  2.040686  -2.324522
999  0.665194   0.690930  5.377604   8.618687

[916 rows x 4 columns]

In [28]:
A=np.random.seed(12346) 
A